---
CORE_EDGE_ROUTER:
  username: admin
  password: admin
  platform: cisco_xr
  port: 22
  connection_options:
    napalm:
      platform: iosxr
      username: admin
      password: admin
    netmiko:
      extras:
        timeout: 4
  data:
    nso:
      authgroup: nso-auth
      protocol: ssh
      ned_id: cisco-iosxr-cli-7.33:cisco-iosxr-cli-7.33
      verification: none
    asn: 65000
XR:
  data: nothing
CSR:
  username: admin
  password: admin
  platform: cisco_xe
  port: 22
  connection_options:
    napalm:
      platform: cisco_xe
      username: admin
      password: admin
  data:
    nso:
      authgroup: nso-auth
      protocol: ssh
      ned_id: cisco-ios-cli-6.69:cisco-ios-cli-6.69
      verification: none
    asn: 65001
