version: "3.8"

services:
  influxdb:
    build: influxdb
    container_name: ${CONTAINER_PREFIX}_influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    restart: on-failure:10
    ports:
      - ${INFLUXDB_INIT_PORT:-8086}:8086
    networks:
      - spauto_devnet_default

  telegraf:
    build: telegraf
    container_name: ${CONTAINER_PREFIX}_telegraf
    privileged: true
    restart: always
    volumes:
      - ${TELEGRAF_CFG_PATH:-./telegraf/telegraf.conf}:/etc/telegraf/telegraf.conf
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - spauto_devnet_default
    ports:
      - 42518:42518

  grafana:
    build: grafana
    container_name: ${CONTAINER_PREFIX}_grafana
    restart: always
    privileged: true
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    networks:
      - spauto_devnet_default
    env_file:
      - .env
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_SECRET_KEY: grafana
      GF_USERS_ALLOW_SIGN_UP: "true"
      GF_USERS_ALLOW_ORG_CREATE: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: grafana
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_DASHBOARDS_JSON_PATH: /opt/grafana

volumes:
  grafana-storage:
  influxdb-storage:


networks:
  spauto_devnet_default:
    external: true
