---
version: "3"
services:
  batfish:
    container_name: "batfish"
    image: "batfish/batfish"
    ports:
      - "9996:9996"
      - "9997:9997"

  spauto:
    container_name: "spauto"
    build:
      context: "."
      target: "spauto"
    depends_on:
      - "batfish"
  # nso:
  #   container_name: "nso"
  #   image: "h4ndzdatm0ld/mpls-sdn-era-nso:5.5-neds"
  #   ports:
  #     - "2024:22"
  #   environment:
  #     - ADMIN_PASSWORD="admin"
  #     - HTTP_ENABLE="True"
  #     - HTTPS_ENABLE="True"
  #   tty: true
