---
version: "3.8"
services:
  batfish:
    container_name: "batfish"
    network_mode: "host"
    image: "batfish/batfish:latest"
    ports:
      - "9996:9996"
  spauto:
    container_name: "spauto"
    network_mode: "host"
    build:
      context: "."
      target: "spauto"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - "batfish"
  clab:
    image: ghcr.io/srl-labs/clab
    network_mode: host
    working_dir: "/src"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/run/netns:/var/run/netns"
      - "/etc/hosts:/etc/hosts"
      - "./:/src"
    pid: "host"
    command: "containerlab deploy -t spauto-clab.yml"
    # If you want to destroy the lab, ovveride the command while executing docker-compose service
    # docker-compose run clab containerlab destroy -t spauto-topology.yml
    # Redeploy
    # docker-compose run clab containerlab deploy -t spauto-topology.yml --reconfigure
    privileged: true
    tty: true
  nso:
    # docker-compose up -d nso // Accessible via web w/ neds (iosxr/xe)
    container_name: "nso"
    image: "h4ndzdatm0ld/mpls-sdn-era-nso:5.5-neds"
    ports:
      - "2024:22"
      - "80:80"
      - "443:443"
      - "830:830"
      - "4334:4334"
      - "4570:4570"
    environment:
      - "ADMIN_PASSWORD=admin"
      - "HTTP_ENABLE=true"
      - "HTTPS_ENABLE=true"
    tty: true
