version: "3.8"

services:
  influxdb:
    # image: influxdb:2.1.1
    image: influxdb:latest
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - tig/.env
    environment:
      INFLUX_DATABASE: "telegraf"
      INLFUX_ADMIN_USER: "grafana"
      INFLUX_ADMIN_PASS: "grafana"
    entrypoint: [ "./entrypoint.sh" ]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT:-8086}:8086
    networks:
      - spauto_devnet_default

  telegraf:
    # image: telegraf:1.19
    image: telegraf:latest
    volumes:
      - ${TELEGRAF_CFG_PATH:-./tig/telegraf/telegraf.conf}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - tig/.env
    depends_on:
      - influxdb
    networks:
      - spauto_devnet_default
    ports:
      - 42518:42518
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "influxdb"
      INFLUXDB_PORT: "8086"
      DATABASE: "telegraf"

  grafana:
    # image: grafana/grafana-oss:8.4.3
    image: grafana/grafana-oss:latest
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    networks:
      - spauto_devnet_default
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_SECRET_KEY: grafana
      GF_USERS_ALLOW_SIGN_UP: "true"
      GF_USERS_ALLOW_ORG_CREATE: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: grafana
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_DASHBOARDS_JSON_PATH: /opt/grafana

volumes:
  grafana-storage:
  influxdb-storage:


networks:
  spauto_devnet_default:
    external: true
