---
version: "3"
services:
  batfish:
    container_name: "batfish"
    image: "batfish/batfish:latest"
    ports:
      - "9996:9996"
      - "9997:9997"
  test_spauto:
    container_name: "test_spauto"
    build:
      context: "."
      target: "test_spauto"
  spauto:
    container_name: "spauto"
    build:
      context: "."
      target: "spauto"
    depends_on:
      - "batfish"
  clab:
    image: ghcr.io/srl-labs/clab
    network_mode: host
    working_dir: "/src"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/run/netns:/var/run/netns"
      - "/etc/hosts:/etc/hosts"
      - "./:/src"
      - "./clab-spauto-mpls-sdn.yml:/src/clab-spauto-mpls-sdn.yml"
    pid: "host"
    command: "containerlab deploy -t spauto-mpls-sdn.yml"
    # If you want to destroy the lab, ovveride the command while executing docker-compose service
    # docker-compose run clab containerlab destroy -t spauto-mpls-sdn.yml
    privileged: true
    tty: true
  nso: # docker-compose up -d nso // Accessible via web w/ neds (iosxr/xe)
    container_name: "nso"
    image: "h4ndzdatm0ld/nso-spauto:5.5-neds"
    ports:
      - "2024:22"
    environment:
      - ADMIN_PASSWORD=admin
      - HTTP_ENABLE=true
      - HTTPS_ENABLE=true
    tty: true
