---
version: "3"
services:
  batfish:
    container_name: "batfish"
    image: "batfish/batfish:test-919"
    ports:
      - "9996:9996"
      - "9997:9997"
  test:
    container_name: "test"
    build:
      context: "."
      target: "test"
  spauto:
    container_name: "spauto"
    build:
      context: "."
      target: "spauto"
    depends_on:
      - "batfish"

  nso:
    container_name: "nso"
    image: "h4ndzdatm0ld/mpls-sdn-era-nso:latest"
    ports:
      - "2024:22"
    environment:
      - ADMIN_PASSWORD=admin
      - HTTP_ENABLE=true
      - HTTPS_ENABLE=true
    tty: true
