---
all:
  children:
    mpls_sdn_era:
      children:
        CORE_EDGE_ROUTER:
          hosts:
            AS65000_P1:
              ansible_host: 192.168.0.170
            AS65000_P2:
              ansible_host: 192.168.0.171
            AS65000_RR1:
              ansible_host: 192.168.0.172
            AS65000_RR2:
              ansible_host: 192.168.0.173
            AS65000_PE1:
              ansible_host: 192.168.0.174
            AS65000_PE2:
              ansible_host: 192.168.0.175
            AS65000_PE3:
              ansible_host: 192.168.0.176
            AS65000_PE4:
              ansible_host: 192.168.0.177
            AS65000_PE100:
              ansible_host: 192.168.0.186
        CSR:
          hosts:
            AS65001_CE1:
              ansible_host: 192.168.0.180
            AS65001_CE2:
              ansible_host: 192.168.0.181
        NTC:
          hosts:
            R1:
              ansible_host: 192.168.0.32
            R2:
              ansible_host: 192.168.0.41
            R3:
              ansible_host: 192.168.0.42
        XR_NETCONF_HOSTS:
          hosts:
            AS65000_P1:
              ansible_host: 192.168.0.174