---
- name: "PAIRED NETWORK DEVICE CNFIG DIFFER"
  hosts: AS65001_CE1
  gather_facts: true
  connection: network_cli
  vars:
    some_var: "Hello Hugo"
  tasks:
    # - name: "TEST"
    #   set_fact:
    #     some_var: "{{ lookup('env', 'RD_OPTION_ANSIBLE_USER') | default('my cool variable', True)}}"
    #   debug:
    #     msg: "{{ some_var }}"

    - name: "55 - CHECKOUT BRANCH IF DIDNT EXIST ON REMOTE"
      ansible.builtin.shell: "git status"
      # args:
      #   chdir: "{{ git_repo_dest }}"
      # when: git_checkout is failed
      register: result

    - debug:
        msg: "{{ result }}"