---
- name: "EXAMPLE NETWORK_CLI PLAYBOOK"
  hosts: "CORE_EDGE_ROUTER"

  tasks:
    - name: "GET BGP NEIGHBORS SUMMARY"
      ansible.netcommon.cli_parse:
        command: "show ip bgp summary"
        parser:
          name: ansible.netcommon.ntc_templates
        set_fact: "bgp_sum"

    - name: "DEBUG"
      debug:
        msg: "IOSXR VERSION: {{ bgp_sum }}"
