# https://docs.ansible.com/ansible/latest/network/user_guide/cli_parsing.html#parsing-with-ntc-templates
---
- name: "EXAMPLE TTP PLAYBOOK"
  hosts: AS65001_CE1
  connection: network_cli

  tasks:

    # - name: "Run command and parse with ttp"
    #   ansible.netcommon.cli_parse:
    #     command: "show lldp neighbors"
    #     parser:
    #       name: ansible.netcommon.ttp
    #     set_fact: lldp

    # - name: DEBUG
    #   debug:
    #     msg: "{{ lldp[0][0]['TOTAL_ENTRIES'] }}"

    - name: "Show Run command and parse with ttp"
      ansible.netcommon.cli_parse:
        command: "show run | sec bgp"
        parser:
          name: ansible.netcommon.ttp
        set_fact: show_run

    - name: DEBUG
      debug:
        msg: "{{ show_run }}"
