---
# ansible_network_os: restconf
ansible_network_os: "ios"
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443
ansible_httpapi_restconf_root: "/restconf/data/"  # default
ansible_httpapi_use_ssl: true
# ansible_connection: "httpapi"
ansible_connection: network_cli

show_commands:
  redundancy_protocols:
    - show glbp
    - show standby
    - show standby capability
    - show standby delay
    - show standby internal
    - show standby neighbors
    - show standby redirect
    - show vrrp
  interface:
    - show ip interface brief
    - show interface
  config:
    - show run
  general_tac:
    - show version
    - show running-config
    - show controllers
    - show stacks
    - show interfaces
    - show buffers
    - show processes memory
    - show processes cpu
