---
ansible_user: admin
ansible_ssh_pass: admin
ansible_python_interpreter: "python3"
ansible_connection: network_cli
ansible_network_os: "ios"
# These commands are vendor specific. Adjust according depending on ansible_network_os/Group.
show_commands:
  redundancy_protocols:
    - show glbp
    - show standby
    - show standby capability
    - show standby delay
    - show standby internal
    - show standby neighbors
    - show standby redirect
    - show vrrp
  interface:
    - show ip interface brief
    - show interface
  config:
    - show run
  general_tac:
    - show version
    - show running-config
    - show controllers
    - show stacks
    - show interfaces
    - show buffers
    - show processes memory
    - show processes cpu
