---
apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    orgId: 1
    url: http://influxdb:8086
    password: "${DOCKER_INFLUXDB_INIT_PASSWORD}"
    user: "${DOCKER_INFLUXDB_INIT_USERNAME}"
    database: "${INFLUXDB_DATABASE}"
    basicAuth: false
    isDefault: true
    jsonData:
      httpMode: POST
      version: Flux
      organization: "${INFLUXDB_ORG}"
    secureJsonData:
      token: "${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"