# yamllint disable rule:truthy
---
name: "Testing CI"

on:
  push:
    branches: ["containerlab", "main"]
  pull_request:
    branches: ["containerlab", "main"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v3"
      - name: "Deploy Batfish"
        run: "docker compose up -d batfish"
      - name: "Lint & Code Format"
        run: |
          echo 'Running Flake8' && \
          poetry run flake8 . && \
          echo 'Running Black' && \
          poetry run black --check --diff . && \
          echo 'Running Yamllint' && \
          poetry run yamllint . && \
          echo 'Running pydocstyle' && \
          poetry run pydocstyle .
      - name: "Run Tests"
        run: "docker compose run spauto"
